In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import datetime
import cvxpy as cp
import sys

In [6]:
sys.path.append('C:\\Users\\hosna\\Documents\\hosna_work_repo\\fingrid_open_data')

In [10]:
import fingrid_api

import importlib

importlib.reload(fingrid_api)

In [25]:
# 1. use your personal key here
key = 'Udl4NFQ3sY7Hlz7gAJmhg7I5cJxTnQuL1PEv2xTu'

# 2. select the desired data's ID
ID = 177

# 3. choose the period of data
from_date = '2022-01-01'
to_date   = '2022-03-01'

# 4. choose the desired format for data (df: DataFrame, otherwise JSON)
desired_format = 'df'

In [26]:
df = fingrid_api.get_ts(api_key= key,
                       var_id = ID,
                       start_time = from_date,
                       end_time = to_date,
                       format= desired_format,
                       )

df

        value                start_time                  end_time
0      49.991  2022-01-01T00:01:00+0000  2022-01-01T00:01:00+0000
1      50.020  2022-01-01T00:04:00+0000  2022-01-01T00:04:00+0000
2      50.019  2022-01-01T00:07:00+0000  2022-01-01T00:07:00+0000
3      50.036  2022-01-01T00:10:00+0000  2022-01-01T00:10:00+0000
4      50.014  2022-01-01T00:13:00+0000  2022-01-01T00:13:00+0000
...       ...                       ...                       ...
28783  50.024  2022-03-01T23:46:00+0000  2022-03-01T23:46:00+0000
28784  50.035  2022-03-01T23:49:00+0000  2022-03-01T23:49:00+0000
28785  50.028  2022-03-01T23:52:00+0000  2022-03-01T23:52:00+0000
28786  50.035  2022-03-01T23:55:00+0000  2022-03-01T23:55:00+0000
28787  50.061  2022-03-01T23:58:00+0000  2022-03-01T23:58:00+0000

[28788 rows x 3 columns]

In [22]:
df_prices = pd.read_csv('prices2022.csv')
df_prices

,Unnamed: 0,time,price_up,price_down,price_da,price_fcr_cap,hour,daynu
0,0,2022-01-01 00:00:00,46.55,29.76,46.60,10.10,0.0,0.0
1,1,2022-01-01 01:00:00,46.60,46.60,41.33,2.50,1.0,0.0
2,2,2022-01-01 02:00:00,41.33,41.33,42.18,2.50,2.0,0.0
3,3,2022-01-01 03:00:00,42.18,42.18,44.37,3.50,3.0,0.0
4,4,2022-01-01 04:00:00,44.37,44.37,37.67,3.00,4.0,0.0
...,...,...,...,...,...,...,...,...
8756,8756,2022-12-31 20:00:00,15.08,15.08,15.08,100.00,20.0,364.0
8757,8757,2022-12-31 21:00:00,11.57,1.34,11.57,60.00,21.0,364.0
8758,8758,2022-12-31 22:00:00,14.89,-7.00,14.89,18.77,22.0,364.0
8759,8759,2022-12-31 23:00:00,9.94,-7.00,9.94,26.76,23.0,364.0
8760,8760,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df_frequencies = pd.read_csv("frequencies2022")
df_frequencies

,Unnamed: 0,index,Alkuaika UTC,Lopetusaika UTC,Alkuaika UTC+02:00,Lopetusaika UTC+02:00,Taajuus - reaaliaikatieto
0,0,0,2021-12-31 22:01:00,2021-12-31 22:01:00,2022-01-01 00:01:00,2022-01-01 00:01:00,49.967
1,1,1,2021-12-31 22:04:00,2021-12-31 22:04:00,2022-01-01 00:04:00,2022-01-01 00:04:00,49.967
2,2,2,2021-12-31 22:07:00,2021-12-31 22:07:00,2022-01-01 00:07:00,2022-01-01 00:07:00,49.964
3,3,3,2021-12-31 22:10:00,2021-12-31 22:10:00,2022-01-01 00:10:00,2022-01-01 00:10:00,49.984
4,4,4,2021-12-31 22:13:00,2021-12-31 22:13:00,2022-01-01 00:13:00,2022-01-01 00:13:00,49.930
...,...,...,...,...,...,...,...
181572,181572,44123,2022-12-31 21:46:00,2022-12-31 21:46:00,2022-12-31 23:46:00,2022-12-31 23:46:00,50.014
181573,181573,44124,2022-12-31 21:49:00,2022-12-31 21:49:00,2022-12-31 23:49:00,2022-12-31 23:49:00,50.003
181574,181574,44125,2022-12-31 21:52:00,2022-12-31 21:52:00,2022-12-31 23:52:00,2022-12-31 23:52:00,50.000
181575,181575,44126,2022-12-31 21:55:00,2022-12-31 21:55:00,2022-12-31 23:55:00,2022-12-31 23:55:00,50.018
181576,181576,44127,2022-12-31 21:58:00,2022-12-31 21:58:00,2022-12-31 23:58:00,2022-12-31 23:58:00,50.001